# version: 0.2
# phases:
#   install:
#     commands:
#       - npm i
#       - npm i -g serverless
      

version: 0.2

phases:
  install:
    commands:
        - npm i
        - npm i -g serverless
  pre_build:
    commands:
        - npm i
  build:
    commands:
        - sls offline --exec 'npm test'
        - mkdir -p target/stg
        - serverless package --package target/stg

artifacts:
  files:
  - target/**/*
  - serverless.yml
  - deploy.sh
